### ISSUE TITLE
Can't reproduce issue in real project

### ISSUE THREAD

**Issue by laurensmiers** [laurensmiers/dummy_ceedling_project#1] opened 2019-11-16 07:34 UTC
Refer to https://github.com/ThrowTheSwitch/CMock/pull/265 for full history.

I updated my debug branch (https://github.com/laurensmiers/CMock/tree/fix_bug_pull_request) to have some more info on when we break out of the loop of inline function matching.
Maybe we are breaking out too soon and that's why only 1 pattern is actually removed?

**Comment by davy79** [comment] 2020-01-08 13:14
Hi @laurensmiers 

I'm a colleague of @Letme and picking up on this mocking of inline functions.
I adapted the example.h file to align it to our project.

However, I can't commit it here due to access restrictions.

I tried to test it locally but ran into issues with ceedling due to the path test/support not existing

```
ERROR: Config path [:paths][:support]['test/support'] does not exist on disk.
```

**Comment by davy79** [comment] 2020-01-08 14:42
Got the test working locally and I'm able to reproduce the issue.

In fact, it seems the top declarations (wrapped in  `#ifndef TEST`) are causing the issue?!?!..
without them, the test passes, but when they are present it fails and we see `static __inline__` in the mocked files.

**Comment by laurensmiers** [comment] 2020-01-08 15:50
Hi,

The access problems should be fixed, I'll have a look at the test/support error later today (unless you fixed it :)?).
Could you push the adapted example.h file that triggers the issue?

**Comment by davy79** [comment] 2020-01-08 16:26
Still could nog push to master... (probably that's intentional)

Anyway, I issued a pull request with my example.h which triggers the issue locally.

**Comment by laurensmiers** [comment] 2020-01-08 18:39
Strange, Added you as collaborator so it should work. Can you check if you received an invite or something? Never done this before on github so not sure how github handles this. It says "Awaiting davy79's response".

Thanks for pushing the example.h .
Might have found a fix for the issue, I'll push it shortly to my cmock branch (https://github.com/laurensmiers/CMock/tree/fix_bug_pull_request). I'll push it to this repo as well, can you check if it fixes the issue (on this project (it should) and your project at work)?
Problem was that I didn't handle inline function declarations at all. I just searched for "static inline" (or whatever pattern the user provided), assumed the next square bracket was the function body of the inline function I just found, and deleted that whole chunk of code between square brackets, f.e.:
```
static inline int func(void);

struct mystruct {
         int a;
};

static inline int func(void) {
        return 42;
}
```
would become:
```
int func(void);

struct mystruct;

static inline int func(void) {
        return 42;
}
```
Which is not the behaviour we want ofcourse. So I reckon that's why removing the function declarations worked.

**Comment by davy79** [comment] 2020-01-08 21:22
Access is OK now! my GitHub account is tied to my personal email address (which I did not check during the day ;-) )

Thanks for the update/fix, I'll check it first thing tomorrow and keep you posted!

**Comment by davy79** [comment] 2020-01-09 09:47
Confirmed the fix to work on the dummy project.

I could not confirm it yet on our main project because now I'm running into a new issue due to the proper stripping... ;-)

In one of the header files of a library we have something like:

```
#define MY_LIBRARY_INLINE static __inline__ __attribute__ ((always_inline)) 
```
And since we have the following inline_function_patterns
```
    :inline_function_patterns:
        - 'MY_LIBRARY_INLINE'
        - 'static __inline__ __attribute__ \(\(always_inline\)\)'
```
everything behind the `#define` is stripped causing an empty define error on compilation.
`error: no macro name given in #define directive`

I don't consider this an error on cmock side but can't see a way to work around this on our side except by adding the `#define` statement to the inline patterns...

Any chance you could check for these `#define` statements and strip the whole line?

**Comment by laurensmiers** [comment] 2020-01-09 12:52
Ha, ok, again something I didn't think about :)...
cmock should ideally not even touch the define's but indeed, it should be ok to get rid of them in the generated header.
I'll have a look later today, should be easy to reproduce. I'll try stripping the `#define` lines, just have to find a safe way to do it.

**Comment by laurensmiers** [comment] 2020-01-09 19:20
I added your define-example but can't trigger the issue since this ceedling project set the test preprocessor to true, so the define is already transformed/gone by the time we transform the inline functions. I'm guessing that in your project this is disabled?
So you can circumvent the issue for now by setting the test processor to true, if you use ceedling:
```
:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
```
If you don't use ceedling, you can add an pre-step to the tests that runs the preprocessor over the headers you will mock.

I usually enable test preprocessing but I can imagine for certain projects, this is not possible.
I'll try to add a unit test in cmock and fix the define-issue further.

**Comment by laurensmiers** [comment] 2020-01-09 21:13
I pushed a possible fix to my cmock branch: https://github.com/laurensmiers/CMock/tree/fix_bug_pull_request . I also pushed it to this project and disabled the test preprocessor to make sure the fix is actually tested.

If you find the time, could you check if it fixes your compile issue?
Thanks for taking the time to test all this stuff :+1:

**Comment by davy79** [comment] 2020-01-10 08:58
Thank you for your effort!

I tested the latest fix, and it seems to do the job but it's not perfect yet.

We have one occasion where the `#define` is wrapped in some pre-processor statements and now the terminating `#endif` statement is stripped.

Here is an example:
```
#if defined (FORCE_INLINE)
/* force function inline */
#define MY_LIBRARY_INLINE static __inline__ __attribute__ ((always_inline))
#else
/* Use call-able implementation */
#define MY_LIBRARY_INLINE
#endif
```

This block is then stripped to:
```
#if defined (FORCE_INLINE)
/* force function inline */
#else
/* Use call-able implementation */
```

It's a bit strange it stripped the `#endif` but leaves the `#else` in place...
Probably because of the "empty" `#define`

I do have some good news as well; when I add those `#define` statements to the `inline_function_patterns` as a workaround.
The build passes, so it seems this is the last hurdle...

**Comment by laurensmiers** [comment] 2020-01-10 12:10
Hmm that's strange, I thought the regex used to delete the second part of the define was able to handle an empty define. But luckily, it should be easily reproducible :).
Will have a look later today.

**Comment by laurensmiers** [comment] 2020-01-11 14:12
Ok, found the issue. I added a regex to cleanup any whitespaces after a user supplied regex (because my programmer-ocd demanded it :)...) however, this regex matched with any-whitespace character, this includes newlines.
So the newline at the end of the empty macro was deleted as well, which caused the cleanup regex to delete the line after the match in case of an empty macro, which in your case was the '#endif'.

I pushed a possible fix to my cmock branch: https://github.com/laurensmiers/CMock/tree/fix_bug_pull_request . And I also pushed it to this project.

Fingers crossed, hopefully this is the last hurdle :)...

**Comment by davy79** [comment] 2020-01-13 08:47
Yes, That did the trick!

We are now able to build all our unit tests and I don't see any weird things anymore in the output.
So as far as I'm concerned this branch can be merged.

now comes the huge task of re-factoring our test code to take advantage of mocked inline functions ;-)
If anything pops up I'll get in touch.

Thanks again for all the effort!

**Comment by laurensmiers** [comment] 2020-01-14 12:12
Great to hear! Thanks for testing the branch.
I'll do some cleanup of the branch and try to merge it into the official cmock.
I might ping you in the final pull request to test the final integrated branch, if you have time ofcourse.

Good luck with the refactor (I feel your pain :)..) and If anything pops up, feel free to poke me.

**Comment by laurensmiers** [comment] 2020-01-14 23:13
I updated my cmock branch to latest upstream master + did some cleanup and refactored how to handle inline function declarations.
@davy79 If you have time, could you do one final test with my latest cmock branch (https://github.com/laurensmiers/CMock/tree/fix_bug_pull_request)? If that checks out, I'll feel confident enough to merge :).

**Comment by davy79** [comment] 2020-01-15 12:04
All looks OK, I get the same results from the latest https://github.com/laurensmiers/CMock/tree/fix_bug_pull_request

**Comment by laurensmiers** [comment] 2020-01-15 15:40
Awesome, thanks for testing!

**Closed as completed** 2020-01-15 20:19 UTC
